name: Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1


    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build

    - name: Generate HTML documentation
      run: bun run docs:build

    - name: Check for broken links
      uses: lycheeverse/lychee-action@v1
      with:
        args: --verbose --no-progress --accept 200,403,429 ./docs/**/*.html
        fail: true

    - name: Upload docs artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: ./docs
        retention-days: 30